// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6BxS0Wg30EnNa-X5dvegUH9Y-CHdahw',
    appId: '1:110707511844:web:51c640aca4915417d23eb1',
    messagingSenderId: '110707511844',
    projectId: 'flutter-firebase-ecommer-aa4d1',
    authDomain: 'flutter-firebase-ecommer-aa4d1.firebaseapp.com',
    storageBucket: 'flutter-firebase-ecommer-aa4d1.firebasestorage.app',
    measurementId: 'G-YDMKW3ERLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoBu3zELxFRTZ3WBb0KlFMLDrCmY0-9xA',
    appId: '1:110707511844:android:f9cf5efd0350c85bd23eb1',
    messagingSenderId: '110707511844',
    projectId: 'flutter-firebase-ecommer-aa4d1',
    storageBucket: 'flutter-firebase-ecommer-aa4d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwp1-s7P5gtNyZCuer6U8UyVTy-4b32FE',
    appId: '1:110707511844:ios:9345b0dcf605b77ad23eb1',
    messagingSenderId: '110707511844',
    projectId: 'flutter-firebase-ecommer-aa4d1',
    storageBucket: 'flutter-firebase-ecommer-aa4d1.firebasestorage.app',
    androidClientId: '110707511844-ntuoeacq6hih85rpfh4bnv58vrkh4lcm.apps.googleusercontent.com',
    iosClientId: '110707511844-s856qltdqmqki03qqttr961righj02tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwp1-s7P5gtNyZCuer6U8UyVTy-4b32FE',
    appId: '1:110707511844:ios:9345b0dcf605b77ad23eb1',
    messagingSenderId: '110707511844',
    projectId: 'flutter-firebase-ecommer-aa4d1',
    storageBucket: 'flutter-firebase-ecommer-aa4d1.firebasestorage.app',
    androidClientId: '110707511844-ntuoeacq6hih85rpfh4bnv58vrkh4lcm.apps.googleusercontent.com',
    iosClientId: '110707511844-s856qltdqmqki03qqttr961righj02tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6BxS0Wg30EnNa-X5dvegUH9Y-CHdahw',
    appId: '1:110707511844:web:2cfabc150d3ea376d23eb1',
    messagingSenderId: '110707511844',
    projectId: 'flutter-firebase-ecommer-aa4d1',
    authDomain: 'flutter-firebase-ecommer-aa4d1.firebaseapp.com',
    storageBucket: 'flutter-firebase-ecommer-aa4d1.firebasestorage.app',
    measurementId: 'G-SZRX2G8NFT',
  );
}
